import { z } from 'zod';

export const createIssueSchema = z.object({
  project_id: z.string().min(1, 'Project is required'),
  title: z.string().min(3, 'Title must be at least 3 characters').max(200),
  description: z.string().min(1, 'Description is required').max(10000),
  issue_type: z.enum(['BUG', 'FEATURE', 'TASK', 'IMPROVEMENT']).default('BUG'),
  priority: z.enum(['P0_CRITICAL', 'P1_HIGH', 'P2_MEDIUM', 'P3_LOW']).default('P2_MEDIUM'),
  severity: z.enum(['BLOCKER', 'CRITICAL', 'MAJOR', 'MINOR', 'TRIVIAL']).default('MAJOR'),
  assignee_id: z.string().optional().nullable(),
  component_id: z.string().optional().nullable(),
  version_id: z.string().optional().nullable(),
  milestone_id: z.string().optional().nullable(),
  environment: z.string().max(500).optional().nullable(),
  repro_steps: z.string().max(5000).optional().nullable(),
  expected_behavior: z.string().max(2000).optional().nullable(),
  actual_behavior: z.string().max(2000).optional().nullable(),
  due_date: z.string().optional().nullable(),
  labels: z.array(z.string()).optional().default([]),
});

export const updateIssueSchema = z.object({
  title: z.string().min(3).max(200).optional(),
  description: z.string().min(1).max(10000).optional(),
  issue_type: z.enum(['BUG', 'FEATURE', 'TASK', 'IMPROVEMENT']).optional(),
  priority: z.enum(['P0_CRITICAL', 'P1_HIGH', 'P2_MEDIUM', 'P3_LOW']).optional(),
  severity: z.enum(['BLOCKER', 'CRITICAL', 'MAJOR', 'MINOR', 'TRIVIAL']).optional(),
  assignee_id: z.string().optional().nullable(),
  component_id: z.string().optional().nullable(),
  version_id: z.string().optional().nullable(),
  milestone_id: z.string().optional().nullable(),
  environment: z.string().max(500).optional().nullable(),
  repro_steps: z.string().max(5000).optional().nullable(),
  expected_behavior: z.string().max(2000).optional().nullable(),
  actual_behavior: z.string().max(2000).optional().nullable(),
  due_date: z.string().optional().nullable(),
  resolution: z.enum(['FIXED', 'WONT_FIX', 'DUPLICATE', 'INVALID', 'CANNOT_REPRODUCE']).optional().nullable(),
  duplicate_of_id: z.string().optional().nullable(),
  labels: z.array(z.string()).optional(),
});

export const queryIssuesSchema = z.object({
  project_id: z.string().optional(),
  project_key: z.string().optional(),
  search: z.string().optional(),
  status: z.string().optional(),
  priority: z.string().optional(),
  severity: z.string().optional(),
  issue_type: z.string().optional(),
  assignee_id: z.string().optional(),
  reporter_id: z.string().optional(),
  component_id: z.string().optional(),
  version_id: z.string().optional(),
  milestone_id: z.string().optional(),
  label: z.string().optional(),
  limit: z.string().optional().transform((v) => (v ? parseInt(v, 10) : 50)),
  offset: z.string().optional().transform((v) => (v ? parseInt(v, 10) : 0)),
  sort_by: z.enum(['created_at', 'updated_at', 'priority', 'severity', 'key', 'due_date']).default('created_at'),
  sort_order: z.enum(['asc', 'desc']).default('desc'),
});
